### ISSUE TITLE
When running docker, merged-SBoM-deep.json saved inside the container

### ISSUE THREAD

**Issue by electricgull** [philips-software/SPDXMerge#41]
When running from docker, merged-SBoM-deep.json is created and left in the container. There needs to be an argument passed for an output directory. 
`
cgriffin@cgriffin-MBP fetch-sboms % docker run -it \
    -v ${PWD}/sbom_dir:/code \
    -e DOCPATH='/code' \
    -e NAME='electricgull-sbom' \
    -e MERGETYPE='1' \
    -e AUTHOR='Cameron Griffin' \
    -e EMAIL='cgriffin@electricgull.com' \
    -e DOCNAMESPACE='https://electricgull.com/' \
    -e FILETYPE=J \
    docker.io/philipssoftware/spdxmerge:v0.1.0
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
arguments:
 - DOCPATH      : /code
 - NAME         : electricgull-sbom
 - MERGETYPE    : 1
 - AUTHOR       : Cameron Griffin
 - EMAIL        : cgriffin@electricgull.com
 - DOCNAMESPACE : https://electricgull.com/
 - FILETYPE     : J
File merged-SBoM-deep.json is generated

cgriffin@cgriffin-MBP fetch-sboms % find ./ -name "merged-SBoM-deep.json"
cgriffin@cgriffin-MBP fetch-sboms % 

cgriffin@cgriffin-MBP fetch-sboms %  docker ps -a |grep spdx
7657298698b5   philipssoftware/spdxmerge:v0.1.0               "/app/entrypoint.sh"     16 seconds ago   Exited (0) 11 seconds ago                                                              bold_franklin

cgriffin@cgriffin-MBP fetch-sboms % docker start bold_franklin; docker exec -it bold_franklin ls
bold_franklin
CHANGELOG.md  CONTRIBUTING.md  Dockerfile  LICENSE  README.md  REPO  TAGS  action.yml  entrypoint.sh  launch.json  merged-SBoM-deep.json  requirements-dev.txt	requirements.txt  src  test
`

**Comment by electricgull** [comment]
Added the following code to provide an option for an output path.  I tested both via the command line and built a container. Both seemed to work fine.  I didn't test the github action.  

https://github.com/philips-software/SPDXMerge/pull/42

**Comment by JeroenKnoops** [comment]
Thanks for the PR. Merged into main in #42
